---
- name: Install apache2 package and update cache
  apt:
        name: apache2
        state: present
        update_cache: yes

- name: Start apache2 service
  service:
        name: apache2
        state: started
        enabled: yes
